backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

site_url: https://netlify-cms-cra.netlify.app
display_url: https://netlify-cms-cra.netlify.app
logo_url: https://netlify-cms-cra.netlify.app/contents/_uploads/icon.png # needs to be a URL to an image file

#publish_mode: editorial_workflow # this will and workflow: draft, in review, ready states
media_folder: "public/contents/_uploads" # Media files will be stored in the repo under public/contents/_uploads
public_folder: "/contents/_uploads" # The src attribute for uploaded media will begin with /contents/_uploads in published site

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    description: The description is a great place for tone setting, high level information, and editing guidelines that are specific to a collection.
    folder: "public/contents/blogposts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "json"
    format: "json"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "faq" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "FAQ" # Used in the UI
    description: The description is a great place for tone setting, high level information, and editing guidelines that are specific to a collection.
    folder: "public/contents/faqs"
    create: true # Allow users to create new documents in this collection
    extension: "json"
    format: "json"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - { label: "Question", name: "title", widget: "string", tagname: "h1" }
      - { label: "Answer", name: "body", widget: "markdown" }
